#!/bin/sh

#
# A simple bash script that uses curl to create a pfSense webGUI session and 
# then uses that session to shut pfSense down. Ideal for use with pwrstatd
# running on another server.
#



# Change these!!
firewallUrl="https://myPfSenseBox.domain.tld"
usr="upsShutdown"
pwd="somePassword"

#!/bin/sh

#Get csrfToken 
csrfToken=$(curl -k -b ~/cookieJar -c ~/cookieJar $firewallUrl 2>/dev/null | grep "name='__csrf_magic'" | egrep -o  "value=\".*\"" | awk -F"\"" '{print $2}')

#Login
curl -k -b ~/cookieJar -c ~/cookieJar --data "login=Login&usernamefld=${usr}&passwordfld=${pwd}&__csrf_magic=$csrfToken" $firewallUrl/index.php &>/dev/null

#Get fresh csrfToken
csrfToken=$(curl -k -b ~/cookieJar -c ~/cookieJar $firewallUrl/halt.php 2>/dev/null | grep "name='__csrf_magic'" | egrep -o  "value=\".*\"" | awk -F"\"" '{print $2}')

#Halt pfSense
curl -k -b ~/cookieJar -c ~/cookieJar --data "Submit= Yes &__csrf_magic=$csrfToken" $firewallUrl/halt.php &>/dev/null

rm -rf ~/cookieJar
